---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
'Twas brillig, and the slithy toves

Did gyre and gimble in the wabe:

All mimsy were the borogoves,

And the mome raths outgrabe.

'Beware the Jabberwock, my son!

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I'm the darkness in the light.

I'm the one who wallows in despair

Trying to find my place in this world.

A world where my sadness is ignored.

I'm the light in the darkness.

I'm the one of few who sees the world for what it is.

A cruel world, where those who hope fail.

A world... where my beliefs are considered false

and those who are against me foolishly are chained to the 

darkness of this world.

Who will save them?

Those who they depend on are chained as well.

Maybe I should free them.

There's no one else.

But hey... why should I care? Chances are... I'm wrong.

And we were meant to fall in despair and corruption.

That is how we are. 
